/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/advanced-components': RouteRecordInfo<'/advanced-components', '/advanced-components', Record<never, never>, Record<never, never>>,
    '/composables': RouteRecordInfo<'/composables', '/composables', Record<never, never>, Record<never, never>>,
    '/destinations': RouteRecordInfo<'/destinations', '/destinations', Record<never, never>, Record<never, never>, '/destinations/' | '/destinations/[id]' | '/destinations/[id]/experience/[slug]'>,
    '/destinations/': RouteRecordInfo<'/destinations/', '/destinations', Record<never, never>, Record<never, never>>,
    '/destinations/[id]': RouteRecordInfo<'/destinations/[id]', '/destinations/:id', { id: ParamValue<true> }, { id: ParamValue<false> }, '/destinations/[id]/experience/[slug]'>,
    '/destinations/[id]/experience/[slug]': RouteRecordInfo<'/destinations/[id]/experience/[slug]', '/destinations/:id/experience/:slug', { id: ParamValue<true>, slug: ParamValue<true> }, { id: ParamValue<false>, slug: ParamValue<false> }>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>, '/users/' | '/users/[id]' | '/users/create'>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/users/[id]': RouteRecordInfo<'/users/[id]', '/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/create': RouteRecordInfo<'/users/create', '/users/create', Record<never, never>, Record<never, never>>,
    '/users.notnested': RouteRecordInfo<'/users.notnested', '/users/notnested', Record<never, never>, Record<never, never>>,
  }
}
